name: Release

on:
  workflow_dispatch:
    inputs:
      draft_release:
        required: true
        type: boolean
        description: Create a draft release
        default: true
      tag:
        required: true
        description: Release tag
        type: string
      release_desc:
        required: false
        type: string
        description: Release Description
      

jobs:
  updater:
    name: Build Updater Tool
    uses: misteraddons/Reflex-Adapt/.github/workflows/updater.yml@actions
  firmware:
    name: Build Firmware
    uses: misteraddons/Reflex-Adapt/.github/workflows/workflow.yml@actions
  assemble:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ updater, firmware ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Updater
        uses: actions/download-artifact@v3
        with:
          name: reflex_updater
      - name: Download Firmware
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: firmware

      - name: Build Release
        run: |
          mkdir -p release/firmware
          cp firmware/*.hex release/firmware/
          cp release_files/* release/
          tar -zxf reflex_updater.tar.gz -O ./x86_64-pc-windows-msvc/reflex_updater.exe > release/reflex.exe
          tar -zxf reflex_updater.tar.gz -O ./x86_64-unknown-linux-musl/reflex_updater > release/reflex-linux-x86_64
          tar -zxf reflex_updater.tar.gz -O ./armv7-unknown-linux-musleabihf/reflex_updater > release/reflex-linux-armv7
          tar -zxf reflex_updater.tar.gz -O ./x86_64-apple-darwin/reflex_updater > release/reflex-macos
          chmod +x release/reflex-macos release/reflex-linux-armv7 release/reflex-linux-x86_64
          ln -s release release-${{ inputs.tag }}

      - name: Zip Archive
        run: zip -r reflex-${{ inputs.tag }}.zip reflex-${{ inputs.tag }}/
        working-directory: release
      - name: Tar Archive
        run: tar -czvf reflex-${{ inputs.tag }}.tar.gz reflex-${{ inputs.tag }}/
        working-directory: release
      - name: Release
        if: ${{ inputs.make_release }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/reflex-${{ inputs.tag }}.tar.gz
            release/reflex-${{ inputs.tag }}.zip
          tag_name: ${{ inputs.tag }}
          body: ${{ inputs.release_desc }}
          draft: ${{ inputs.draft_release }}


