name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Release tag
        type: string
      make_release:
        required: true
        type: boolean
        description: Create a Github release

jobs:
  updater:
    uses: misteraddons/Reflex-Adapt/.github/workflows/updater.yml@actions
  build:
    runs-on: ubuntu-latest
    needs: updater
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install arduino platform
        run: arduino-cli core install arduino:avr
      - name: Download Updater
        uses: actions/download-artifact@v3
        with:
          name: reflex_updater
      - name: Build Release
        run: make release
      - name: Listing
        run: ls -lR release/
      - name: Zip Archive
        run: zip -r reflex-${{ inputs.tag }}.zip reflex/
        working-directory: release
      - name: Tar Archive
        run: tar -czvf reflex-${{ inputs.tag }}.tar.gz reflex/
        working-directory: release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: reflex
          path: release/reflex-${{ inputs.tag }}.tar.gz
          if-no-files-found: error
      - name: Release
        if: ${{ inputs.make_release }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/reflex-${{ inputs.tag }}.tar.gz
            release/reflex-${{ inputs.tag }}.zip
          tag_name: $${{ inputs.tag }}


